export { default as Hero } from "./Hero/Hero";
export { default as WhyItMatters } from "./WhyItMatters/WhyItMatters";
export { default as Innovation } from "./Innovation/Innovation";
export { default as WorldConnect } from "./WorldConnect/WorldConnect";
export { default as Empowering } from "./Empowering/Empowering";
export { default as HowItWorks } from "./HowItWorks/HowItWorks";
export { default as Banner } from "./Banner/Banner";
export { default as Faq } from "./Faq/Faq";
export { default as FooterNav } from "./FooterNav/FooterNav";
